#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: Shreyas Vaidyanath  
name: Shreyas Vaidyanath

# Short bio or description (displayed in the header)
description: Aspiring Data Scientist

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/shreyas1701/shreyas1701.github.io/master/images/favicon-jekyll-140x140.png

#
# Flags below are optional


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: shreyas1701
  instagram:
  linkedin: shreyasvaidyanath
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: shreyas1701
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  medium: shreyas1701


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: shreyas1701

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-130842750-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://shreyas1701.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
theme: minima
# remote_theme: samesies/barber-jekyll

permalink: /:title/

# The release of Jekyll Now that you're using
version: v3.7.4

# Medium token for cross-posting
MEDIUM_USER_ID: '1dc243f79a1a2c256b2f68751ec3b1029ff277e5dae173533c1ec49aebb2a1111'
jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: public
  license: all-rights-reserved

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-twitter-plugin #twitter plugin
  - jekyll-paginate-v2 #Pagination
  - jekyll-google-photos #Link to GPhotos


collections:
  projects:
    output: true
  foodposts:
    output: true
    
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

autopages:

  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: False